# Generated by Django 4.1.6 on 2023-02-15 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'uživatel',
                'verbose_name_plural': 'uživatelé',
            },
        ),
        migrations.CreateModel(
            name='Pojistenec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=20, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=50, verbose_name='Příjmení')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('telefon', models.IntegerField(default=0, verbose_name='Telefon')),
                ('ulice', models.CharField(max_length=100, verbose_name='Ulice a číslo popisné')),
                ('mesto', models.CharField(max_length=50, verbose_name='Město')),
                ('psc', models.IntegerField(default=0, verbose_name='PSČ')),
            ],
            options={
                'verbose_name': 'Pojištěnec',
                'verbose_name_plural': 'Pojištěnci',
            },
        ),
        migrations.CreateModel(
            name='Pojisteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_pojisteni', models.CharField(max_length=80, verbose_name='Typ pojištění')),
                ('popis_pojisteni', models.CharField(max_length=400, verbose_name='Popis produktu')),
            ],
            options={
                'verbose_name': 'Pojištění',
                'verbose_name_plural': 'Pojištění',
            },
        ),
        migrations.CreateModel(
            name='PojistnaUdalost',
            fields=[
                ('cislo_pojistne_udalosti', models.AutoField(primary_key=True, serialize=False, verbose_name='Číslo pojistné události')),
                ('pojistna_udalost', models.CharField(max_length=300, verbose_name='Pojistná událost')),
                ('vyplacena_castka', models.FloatField(default=0, verbose_name='Vyplacená částka')),
                ('pojistenec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insuremonkey.pojistenec', verbose_name='Pojištěnec')),
            ],
            options={
                'verbose_name': 'Pojistná událost',
                'verbose_name_plural': 'Pojistné události',
            },
        ),
        migrations.CreateModel(
            name='NastavitPojisteni',
            fields=[
                ('cislo_smlouvy', models.AutoField(primary_key=True, serialize=False, verbose_name='Čislo smlouvy')),
                ('predmet_pojisteni', models.CharField(max_length=200, verbose_name='Předmět pojištění')),
                ('datum_zacatek', models.DateField(verbose_name='Platnost od')),
                ('datum_konec', models.DateField(verbose_name='Platnost do')),
                ('castka', models.FloatField(default=0, verbose_name='Částka')),
                ('pojistenec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insuremonkey.pojistenec', verbose_name=' ')),
                ('pojisteni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insuremonkey.pojisteni', verbose_name='Typ pojištění')),
            ],
            options={
                'verbose_name': 'Smluvené pojištění',
                'verbose_name_plural': 'Smluvená pojištění',
            },
        ),
    ]
